theme: jekyll-theme-minimal
title: Downtown Apartment - Airbnb
description: Your perfect downtown getaway - beautifully designed apartment in the heart of the city
show_downloads: false
google_analytics: 
